# Generated by Django 3.2.5 on 2022-08-03 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='group',
            new_name='team',
        ),
    ]
