# Generated by Django 3.2.5 on 2022-08-01 12:16

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=20)),
                ('real_name', models.CharField(max_length=20)),
                ('description', models.CharField(default='', max_length=255)),
                ('headshot', models.ImageField(blank=True, null=True, upload_to=user.models.user_directory_path)),
            ],
        ),
    ]
