# Generated by Django 3.2.5 on 2022-08-03 11:57

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('mailbox', models.EmailField(default='', max_length=254, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=20)),
                ('real_name', models.CharField(max_length=20)),
                ('password', models.CharField(default='', max_length=20)),
                ('description', models.CharField(default='', max_length=255)),
                ('sex', models.CharField(default='', max_length=5)),
                ('headshot', models.ImageField(blank=True, null=True, upload_to=user.models.user_directory_path)),
            ],
        ),
    ]
